Travel_ASP/ViewModels/SettingViewModel.cs
namespace Travel_ASP.ViewModels
{
    public class SettingViewModel
    {
        public IFormFile? DefaultTourImage { get; set; }
        public IFormFile? DefaultBlogImage { get; set; }
        public string? AppName { get; set; }
        public string? Phone { get; set; }
        public string? Email { get; set; }
    }
}

Travel_ASP/Controllers/SettingController.cs
using Microsoft.AspNetCore.Mvc;
using STM.DataAccess.Contexts;
using Travel_ASP.ViewModels;

namespace Travel_ASP.Controllers
{
    public class SettingController : Controller
    {
        private readonly TravelDbContext _db;

        public SettingController(TravelDbContext db)
        {
            _db = db;
        }

        [HttpGet("admin/settings")]
        public IActionResult Index()
        {
            var settingApp = _db.Configurations.FirstOrDefault(x => x.Key == "appName");
            var settingEmail = _db.Configurations.FirstOrDefault(x => x.Key == "email");
            var settingPhone = _db.Configurations.FirstOrDefault(x => x.Key == "phone");
            var data = new SettingViewModel()
            {
                AppName = settingApp.Value,
                Email = settingEmail.Value,
                Phone = settingPhone.Value,
            };
            return View(data);
        }


        [HttpPost("admin/settings/save")]
        public IActionResult Save(SettingViewModel dto)
        {
            string path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/uploads");

            if (!Directory.Exists(path))
                Directory.CreateDirectory(path);

            if (dto.DefaultBlogImage != null)
            {
                var setting = _db.Configurations.FirstOrDefault(x => x.Key == "defaultBlogImage");
                string fileName = string.Empty;

                FileInfo fileInfo = new FileInfo(dto.DefaultBlogImage.FileName);
                fileName = dto.DefaultBlogImage.FileName;

                string fileNameWithPath = Path.Combine(path, fileName);

                using (var stream = new FileStream(fileNameWithPath, FileMode.Create))
                {
                    dto.DefaultBlogImage.CopyTo(stream);
                }
                setting.Value = fileName;
                _db.Configurations.Update(setting);
            }

            if (dto.DefaultTourImage != null)
            {
                var setting = _db.Configurations.FirstOrDefault(x => x.Key == "defaultTourImage");
                string fileName = string.Empty;

                FileInfo fileInfo = new FileInfo(dto.DefaultTourImage.FileName);
                fileName = dto.DefaultTourImage.FileName;

                string fileNameWithPath = Path.Combine(path, fileName);

                using (var stream = new FileStream(fileNameWithPath, FileMode.Create))
                {
                    dto.DefaultTourImage.CopyTo(stream);
                }
                setting.Value = fileName;
                _db.Configurations.Update(setting);
            }

            var settingAppName = _db.Configurations.FirstOrDefault(x => x.Key == "appName");
            if (settingAppName != null)
            {
                settingAppName.Value = dto.AppName;
                _db.Configurations.Update(settingAppName);
            }

            var settingEmail = _db.Configurations.FirstOrDefault(x => x.Key == "email");
            if (settingEmail != null)
            {
                settingEmail.Value = dto.Email;
                _db.Configurations.Update(settingEmail);
            }

            var settingPhone = _db.Configurations.FirstOrDefault(x => x.Key == "phone");
            if (settingPhone != null)
            {
                settingPhone.Value = dto.Phone;
                _db.Configurations.Update(settingPhone);
            }

            _db.SaveChanges();
            ViewData["Message"] = "Cập nhật thông tin website thành công";
            return RedirectToAction("Index");
        }
    }
}

Travel_ASP/Views/Setting/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout_admin.cshtml";
    var message = ViewData["Message"] as string;
}

@model Travel_ASP.ViewModels.SettingViewModel

<div class="card">
    @if (!string.IsNullOrEmpty(message))
    {
        <div class="row">
            <div class="col-md-12">
                <div class="alert alert-success">
                    @message
                </div>
            </div>
        </div>
    }
    <form asp-action="Save" asp-controller="Setting" method="POST" enctype="multipart/form-data">
        <div class="card-body">
            <div class="block-content">
                <div class="row">
                    <div class="form-group col-md-6 mt-20">
                        <label class="col-md-12">
                            Ảnh tour mặc định
                        </label>
                        <div class="col-md-12">
                            <input type="file" asp-for="DefaultTourImage" class="dropify">
                        </div>
                    </div>
                    <div class="form-group col-md-6 mt-20">
                        <label class="col-md-12">
                            Ảnh bài viết mặc định
                        </label>
                        <div class="col-md-12">
                            <input type="file" asp-for="DefaultBlogImage" class="dropify">
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="form-group col-md-12 mt-20">
                        <label class="col-md-12">
                            Tên website
                        </label>
                        <div class="form-material col-md-12">
                            <input type="text" asp-for="AppName" class="form-control"
                                   placeholder="Tên website">
                        </div>
                    </div>
                    <div class="form-group col-md-12 mt-20">
                        <label class="col-md-12">
                            Email
                        </label>
                        <div class="form-material col-md-12">
                            <input type="email" asp-for="Email" class="form-control"
                                   placeholder="Email">
                        </div>
                    </div>
                    <div class="form-group col-md-12 mt-20">
                        <label class="col-md-12">
                            Số điện thoại
                        </label>
                        <div class="form-material col-md-12">
                            <input type="number" asp-for="Phone" class="form-control"
                                   placeholder="Số điện thoại">
                        </div>
                    </div>

                </div>
            </div>
        </div>
        <div class="card-footer text-right">
            <div class="col-md-12 mb-20">
                <a  asp-action="Index" asp-controller="Dashboard" class="btn btn-danger">
                   Hủy bỏ
                </a>
                <button class="btn btn-primary" type="submit">Cập nhật</button>
            </div>
        </div>
    </form>
</div>